name: spacy-gliner
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - gliner>=0.2.0
    - spacy>=3.0.0
    - torch>=2.0.0
    - transformers>=4.30.0
    - huggingface-hub>=0.15.0
    - tabulate>=0.9.0