#!/bin/bash

echo "Setting up spacy-gliner conda environment..."
echo "================================================"
echo ""
echo "Run the following commands in your terminal:"
echo ""
echo "# Create the environment"
echo "conda create --name spacy-gliner python=3.10 -y"
echo ""
echo "# Activate the environment"
echo "conda activate spacy-gliner"
echo ""
echo "# Install dependencies"
echo "pip install gliner>=0.2.0 spacy>=3.0.0 torch>=2.0.0 transformers>=4.30.0 huggingface-hub>=0.15.0 tabulate>=0.9.0"
echo ""
echo "# Or use the requirements file:"
echo "pip install -r requirements.txt"
echo ""
echo "================================================"
echo "After setup, test with:"
echo "python extract_pii.py --filter --anonymize --resolve-entities"